---
title: "practica de uso de paquete dplyr"
author: "Franchesca Moraga"
format: html
toc: true 
lang: es
theme: solar
---

# Introduccion 
Este documento contiene algunos ejemplos de uso de las funciones del paquete dplyr de [Tidyverse] (https//www.tydyverse.org/)


#Carga de paquetes 

```{r}
#| label: carga-paquetes
#| message : false
#| warning: false

library(tidyverse)
library(palmerpenguins)
library(knitr)
```

# Carga de datos 

```{r}
#|label: carga-datos
#| message : false
#| warning: false

delitos_2023 <- read_csv("estadisticaspoliciales2023.csv", locale = locale(encoding = "WINDOWS-1252"))

```


# select

## Ejemplos 1

```{r}
#| label: select-01

# select(penguins, spacies, bill_lengh_mm, sex)

penguins |>
  select(species, bill_length_mm, sex) |>
  head(10) |>
  kable()
```

## Ejemplos 2

```{r}
#| label: select-2

penguins |>
  select(
    especie = species,
    logitud_pico_mm = bill_length_mm, sex) |> 
  head(10) |>
  kable()
```
    
   

# filter()

## Ejemplo 1


```{r}
#| label: fillter-01

penguins |>
  select( species, island, sex) |>
  filter(species == "Adelie") |>
  filter(sex == "male") |> 
  filter(island == "Torgersen") |>
  kable() 
```

## Ejemplon 2

```{r}
#| label: filter-02

# Delitos cometidos a vehiculos en el cantón de Montes de Oca 
delitos_2023 |>
  select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |>
  filter(Canton == "MONTES DE OCA" & Victima == "VEHICULO" ) |>
  kable()
```

## Ejemplo 3

```{r}
#| label: filter-03

# Asaltos cometidos en San Pedro de Montes de Oca
delitos_2023 |>
  select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |>
  filter(Delito == "ASALTO" & Distrito == "SAN PEDRO" & Canton == "MONTES DE OCA") |>
  kable()
```

## Ejemplo 4


```{r}
#| label: filter-04

# Asaltos Y homicios cometidos en San Pedro de Montes de Oca
delitos_2023 |>
  select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |>
  filter((Distrito == "SAN PEDRO" & Canton == "MONTES DE OCA" & Delito == "ASALTO" | Delito == "HOMICIDIO")) |>
  kable()
```

# arrange()

## Ejemplo 1

```{r}
#| label: arrange-01

penguins |> 
  select(species, bill_length_mm, bill_depth_mm)|>
  head(12) |>
    arrange(bill_length_mm, bill_depth_mm)|>
  kable()

```

# mutate ()


```{r}
#| label: mutate-01

penguins |> 
  select(species,sex, body_mass_g)|>
  mutate(body_mass_kg = body_mass_g/1000)|>
    mutate(body_mass_lb = body_mass_kg*2.2)|>
  head(12) |>
  kable()

```

# Ejemplo 2

```{r}
#| label: mutate-02

delitos_2023 |>
  select(Delito, SubDelito,Fecha, Hora, Canton) |>
  mutate(Fecha_Date = as.Date(delitos_2023$Fecha, format="%d/%m/%Y"))|>
  filter(Canton == "MONTES DE OCA") |>
  arrange(Fecha_Date)|>
  kable()

```

# summarize

## Ejemplo 1

```{r}
# label: summarize-01

# Peso promedio por especie de pinguinos

penguins |> 
  group_by(species) |>
  summarize(
    body_mass_g_mean = mean(body_mass_g,na.rm = TRUE),
    body_mass_g_min = min(body_mass_g, na.rm = TRUE),
     body_mass_g_mAX = max(body_mass_g, na.rm = TRUE),
    cantidad_pinguinos = n()
    ) |>
  kable()
```


```{r}
#| label: aggregate-01

aggregate(
  body_mass_g ~ species,
  data = penguins, 
  FUN = mean
  
)
```

## Ejemplo 2

```{r}
#| label: summarize-02

# Cantidad d ehomicidios por provincia y canton
delitos_2023 |>
  filter(Delito == "HOMICIDIO") |>
  group_by(Provincia, Canton, Distrito, Genero) |>
   summarize(homicidios_2023 = n()
             )|>
  arrange(desc(homicidios_2023)) |>
      kable()      
```

## Ejemplo 3

```{r}
#| label: summarize-03

delitos_2023 |>
  filter(Delito == "HOMICIDIO") |>
group_by(Genero) |>
  summarize(n= n()) |>
  kable()
```

## Ejemplo 4 

```{r}
#| label: summarize-04

delitos_2023 |>
  filter(Delito == "HOMICIDIO") |>
group_by(Nacionalidad) |>
  summarize(n= n()) |>
  arrange(desc(n)) |>
  kable()
```

# Ejemplo 5
```{r}
#| label: summarize-05

# Promedio de masa y n cantisdad de registros de pinguinos

penguins |>
  summarize(body_mass_g_mean = mean(body_mass_g, na.rm = TRUE),
            n = n()) |>
  kable()
```


```{r}
